//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHEQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class beneficiaros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public beneficiaros()
        {
            this.cheques = new HashSet<cheques>();
        }
    
        public string id_beneficiario { get; set; }
        public string NomBeneficiaro { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string estatus { get; set; }
        public string firma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cheques> cheques { get; set; }
    }
}
