//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHEQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheques
    {
        public string folio { get; set; }
        public string id_banco { get; set; }
        public System.DateTime fecha { get; set; }
        public string id_benefeciario { get; set; }
        public string cantidad { get; set; }
    
        public virtual banco banco { get; set; }
        public virtual beneficiaros beneficiaros { get; set; }
    }
}
